export const GET_LANGUAGE = "GET_LANGUAGE";
export const TOGGLE_CONTACT = "TOGGLE_CONTACT"
export const TOGGLE_CONTACT_CLOSE = "TOGGLE_CONTACT_CLOSE"

export const CHANGE_CATEGORY = "CHANGE_CATEGORY";

export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";


